name: Run Serenity Tests

on:
  push:
    branches:
      - api-test-ravindu

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        # Start the API server on port 8080 using the JAR file in the resources folder
      - name: Start API server
        run: |
            nohup java -jar src/main/resources/libs/demo-0.0.1-SNAPSHOT.jar --server.port=8080 &

      # Start the API server on a 8080
      - name: Start API server
        run: |
          nohup java -jar demo-0.0.1-SNAPSHOT.jar --server.port=8080 &

      # Wait for the API to start
      - name: Wait for API to start
        run: sleep 15

      # Run Serenity tests
      - name: Run Serenity tests
        run: |
          mvn clean verify

      # Stop the API server
      - name: Stop API server
        run: |
          pkill -f 'java -jar demo-0.0.1-SNAPSHOT.jar'
