name: Run Tests

on:
  push:
    branches:
      - api-test-ravindu

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: API
        run: |
          nohup java -jar $(pwd)/src/test/resources/libs/demo-0.0.1-SNAPSHOT.jar --server.port=8080 &

      # Wait for the API to start
      - name: Wait for API to start
        run: sleep 5

      - name: Run Serenity tests
        run: |
          mvn clean verify
