name: Run Serenity Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (adjust Java version if needed)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Start the API server on a specific port
      - name: Start API server
        run: |
          nohup java -jar demo-0.0.1-SNAPSHOT.jar --server.port=8080 &

      # Wait for the API to start
      - name: Wait for API to start
        run: sleep 10

      # Run Serenity tests
      - name: Run Serenity tests
        run: |
          mvn clean verify

      # stop the API server
      - name: Stop API server
        run: |
          pkill -f 'java -jar demo-0.0.1-SNAPSHOT.jar'
