name: Run Serenity Tests

on:
  push:
    branches:
      - fixes
      - master
      - enhancements-fixes
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow write access to repository contents

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Make chromedriver executable
      - name: Make chromedriver executable
        run: chmod +x $(pwd)/src/test/resources/drivers/chromedriver

      # Install required dependencies and Chrome
      - name: Install Dependencies and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxi6 libxrandr2 libgbm1 libasound2 libu2f-udev
          sudo apt-get install -y libicu70
          
          # Download and install Google Chrome for Testing
          export CHROME_VERSION=131.0.6778.204
          curl -sSL https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-headless-shell-linux64.zip -o chrome-headless-shell-linux64.zip
          unzip chrome-headless-shell-linux64.zip
          
          # Move the 'chrome-headless-shell' binary to /usr/bin
          if [ -f "chrome-headless-shell-linux64/chrome-headless-shell" ]; then
            sudo mv chrome-headless-shell-linux64/chrome-headless-shell /usr/bin/google-chrome
          else
            echo "Chrome binary not found in the expected location."
            exit 1
          fi

          # Verify installation
          google-chrome --version

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Modify serenity.properties to set chromedriver path and enable headless mode
      - name: Update serenity.properties
        run: |
          # Set the chromedriver path and headless mode in serenity.properties
           sed -i 's|webdriver.chrome.driver=src/test/resources/drivers/chromedriver.exe|webdriver.chrome.driver=src/test/resources/drivers/chromedriver|'  $(pwd)/serenity.properties
           sed -i 's|headless.mode=false|headless.mode=true|' $(pwd)/serenity.properties
          # Display the contents of the serenity.properties file after the changes
           echo "Updated serenity.properties file:"     
           cat $(pwd)/serenity.properties


      # Start the API server on port 8080 using the JAR file in the resources folder
      - name: Start API server
        run: |
          nohup java -jar $(pwd)/src/test/resources/libs/demo-0.0.1-SNAPSHOT.jar --server.port=8080 &

      # Wait for the API to start
      - name: Wait for API to start
        run: sleep 15

      # Run Serenity tests
      - name: Run Serenity tests
        run: |
          mvn clean verify
        continue-on-error: true

      # Upload Serenity reports as artifact
      - name: Upload Serenity reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-reports
          path: target/site/serenity